
project:
  type: website
  output-dir: docs
  render:
  - "index.qmd"
  - "content/**"
lang: de


website:
  title: "Argumentlandkarten"
  description: "Kontroversen begleiten mit Argumentlandkarten"
  favicon: ""

  navbar:
    background: primary
    search: true
    left:
      - text: "Das Projekt"
        href: index.qmd
      - text: "Das Team"
        href: content/team.qmd
      - text: "Themen & Bausteine"
        menu:
          - text: "Baukasten Argumentkartierung"
            href: content/baukasten_argumentkartierung.qmd
          - text: "Grundlagenseminare"
            href: content/grundlagenseminare.qmd

  page-footer:
    left: 
      - "Argumentlandkarten"
    right:
      - content/impressum.qmd
      - text: 'Gebaut mit <a href="https://quarto.org">Quarto</a>'

format:
  html:
    respect-user-color-scheme: true
    template-partials:
      - assets/partials/title-block.html
    theme:
      light: flatly
      dark: darkly
    toc-depth: 3
    argdown:
      mode: web-component
      sourceHighlighter: web-component
      config: argdown.config.json
  pdf:
    documentclass: article
    pdf-engine-opt: "-shell-escape"
    papersize: a4
    toc: false
    include-in-header: assets/latex/_handout-packages.tex
    template-partials:
      - assets/latex/before-body.tex
    syntax-definitions:
      - assets/pandoc/argdown.xml
    syntax-highlighting: assets/pandoc/argdown.theme

execute:
  freeze: auto

filters:
  - ./node_modules/.bin/argdown-filter
  
argdown:
  mode: inline
  format: svg
  config: argdown.config.json
